<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Jabatan extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Jabatan_model');
		$this->load->library('form_validation');
	}

	public function index()
	{
		$q = urldecode($this->input->get('q', TRUE));
		$start = intval($this->input->get('start'));

		if ($q <> '') {
			$config['base_url'] = base_url() . 'jabatan/index.html?q=' . urlencode($q);
			$config['first_url'] = base_url() . 'jabatan/index.html?q=' . urlencode($q);
		} else {
			$config['base_url'] = base_url() . 'jabatan/index.html';
			$config['first_url'] = base_url() . 'jabatan/index.html';
		}

		$config['per_page'] = 10;
		$config['page_query_string'] = TRUE;
		$config['total_rows'] = $this->Jabatan_model->total_rows($q, TRUE);
		$jabatan = $this->Jabatan_model->get_limit_data($config['per_page'], $start, $q, TRUE);

		$this->load->library('pagination');
		$this->pagination->initialize($config);

		$data = array(
			'jabatan_data' => $jabatan,
			'q' => $q,
			'pagination' => $this->pagination->create_links(),
			'total_rows' => $config['total_rows'],
			'start' => $start,
		);

		$this->load->view('jabatan/jabatan_list', $data);
	}

	public function read($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);
		if ($row && empty($row->deleted_at)) {
			$data = array(
				'id_jabatan' => $row->id_jabatan,
				'nama_jabatan' => $row->nama_jabatan,
				'created_at' => $row->created_at,
				'updated_at' => $row->updated_at,
				'deleted_at' => $row->deleted_at,
			);
			$this->load->view('jabatan/jabatan_read', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found or Deleted');
			redirect(site_url('jabatan'));
		}
	}

	public function create()
	{
		$data = array(
			'button' => 'Create',
			'action' => site_url('jabatan/create_action'),
			'id_jabatan' => set_value('id_jabatan'),
			'nama_jabatan' => set_value('nama_jabatan'),
		);
		$this->load->view('jabatan/jabatan_form', $data);
	}

	public function create_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->create();
		} else {
			$data = array(
				'nama_jabatan' => $this->input->post('nama_jabatan', TRUE),
				'created_at' => date('Y-m-d H:i:s'),
				'updated_at' => NULL,
				'deleted_at' => NULL,
			);

			$this->Jabatan_model->insert($data);
			$this->session->set_flashdata('message', 'Create Record Success');
			redirect(site_url('jabatan'));
		}
	}

	public function update($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);

		if ($row) {
			$data = array(
				'button' => 'Update',
				'action' => site_url('jabatan/update_action'),
				'id_jabatan' => set_value('id_jabatan', $row->id_jabatan),
				'nama_jabatan' => set_value('nama_jabatan', $row->nama_jabatan),
			);
			$this->load->view('jabatan/jabatan_form', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jabatan'));
		}
	}

	public function update_action()
	{
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->update($this->input->post('id_jabatan', TRUE));
		} else {
			$data = array(
				'nama_jabatan' => $this->input->post('nama_jabatan', TRUE),
				'updated_at' => date('Y-m-d H:i:s'),
			);

			$this->Jabatan_model->update($this->input->post('id_jabatan', TRUE), $data);
			$this->session->set_flashdata('message', 'Update Record Success');
			redirect(site_url('jabatan'));
		}
	}

	public function delete($id)
	{
		$row = $this->Jabatan_model->get_by_id($id);

		if ($row) {
			$data = array(
				'deleted_at' => date('Y-m-d H:i:s'),
			);

			$this->Jabatan_model->update($id, $data);
			$this->session->set_flashdata('message', 'Delete Record Success');
			redirect(site_url('jabatan'));
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('jabatan'));
		}
	}

	public function _rules()
	{
		$this->form_validation->set_rules('nama_jabatan', 'nama jabatan', 'trim|required');

		$this->form_validation->set_rules('id_jabatan', 'id_jabatan', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Jabatan.php */
/* Location: ./application/controllers/Jabatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-11 18:53:06 */
/* http://harviacode.com */
