# Generated by Django 3.2.25 on 2025-05-06 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sipreti.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sipreti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAbsensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_absensi', models.IntegerField(choices=[(0, 'Harian'), (1, 'Dinas')])),
                ('check_mode', models.IntegerField(choices=[(0, 'Check-in'), (1, 'Check-out')])),
                ('waktu_absensi', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nama_lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_kamera', models.CharField(blank=True, max_length=255, null=True)),
                ('url_foto_presensi', models.CharField(blank=True, max_length=255, null=True)),
                ('url_dokumen', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_absensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadiusAbsen',
            fields=[
                ('id_radius', models.AutoField(primary_key=True, serialize=False)),
                ('ukuran', models.FloatField()),
                ('satuan', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'radius_absen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KompresiHuffman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('frequency_model', models.TextField()),
                ('code_table', models.TextField()),
                ('compressed_file', models.BinaryField()),
                ('compression_type', models.CharField(default='huffman', max_length=50)),
                ('original_length', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_size', models.IntegerField(default=0)),
                ('compressed_size', models.IntegerField(default=0)),
                ('compression_ratio', models.FloatField(default=0.0)),
                ('compression_time_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'kompresihuffman',
            },
        ),
        migrations.AlterModelOptions(
            name='biometrik',
            options={'verbose_name_plural': 'Biometrik'},
        ),
        migrations.AlterField(
            model_name='biometrik',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sipreti.models.image_upload_path),
        ),
        migrations.CreateModel(
            name='UserAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=255)),
                ('device_brand', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('device_os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_sdk_version', models.CharField(blank=True, max_length=10, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_android',
                'unique_together': {('id_pegawai', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id_unit_kerja', models.AutoField(primary_key=True, serialize=False)),
                ('nama_unit_kerja', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius', models.ForeignKey(blank=True, db_column='id_radius', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sipreti.radiusabsen')),
            ],
            options={
                'db_table': 'unit_kerja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_jabatan', models.ForeignKey(db_column='id_jabatan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sipreti.jabatan')),
                ('id_unit_kerja', models.ForeignKey(db_column='id_unit_kerja', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sipreti.unitkerja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pegawai',
                'db_table': 'pegawai',
            },
        ),
        migrations.AlterField(
            model_name='biometrik',
            name='id_pegawai',
            field=models.ForeignKey(db_column='id_pegawai', on_delete=django.db.models.deletion.CASCADE, to='sipreti.pegawai'),
        ),
    ]
