# Generated by Django 3.2.25 on 2025-05-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipreti', '0002_auto_20250506_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompresihuffman',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kompresihuffman',
            name='is_rgb',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LogVerifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('nilai_kecocokan', models.FloatField(blank=True, null=True)),
                ('waktu_dekompresi_ms', models.IntegerField()),
                ('waktu_verifikasi_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kompresi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipreti.kompresihuffman')),
            ],
            options={
                'db_table': 'logverifikasi',
            },
        ),
    ]
