# Generated by Django 3.2.25 on 2025-06-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipreti', '0005_auto_20250602_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompresihuffman',
            name='frequency_model',
            field=models.TextField(default='{}'),
        ),
    ]
