<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Log_absensi_model extends CI_Model
{

	public $table = 'log_absensi';
	public $id = 'id_log_absensi';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	function get_all_with_pegawai()
	{
		$this->db->select('log_absensi.*, pegawai.nama, pegawai.nip');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = log_absensi.id_pegawai', 'left');
		$this->db->order_by($this->id, $this->order);
		return $this->db->get()->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	function get_by_id_with_pegawai($id)
	{
		$this->db->select('log_absensi.*, pegawai.nama, pegawai.nip');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = log_absensi.id_pegawai', 'left');
		$this->db->where($this->id, $id);
		return $this->db->get()->row();
	}

	// get total rows
	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('id_pegawai', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('id_pegawai', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	public function get_limit_data_with_pegawai($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->select('log_absensi.*, pegawai.nama, pegawai.nip');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = log_absensi.id_pegawai', 'left');
		
		if ($q) {
			// Search bisa di nama pegawai atau id_pegawai
			$this->db->group_start();
			$this->db->like('log_absensi.id_pegawai', $q);
			$this->db->or_like('pegawai.nama', $q);
			$this->db->group_end();
		}
		
		if ($onlyActive) {
			$this->db->where('(log_absensi.deleted_at IS NULL OR log_absensi.deleted_at = "")');
		}
		
		$this->db->limit($limit, $start);
		$this->db->order_by($this->id, $this->order);
		return $this->db->get()->result();
	}

	function total_rows_with_pegawai($q = NULL, $onlyActive = FALSE)
	{
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = log_absensi.id_pegawai', 'left');
		
		if ($q) {
			$this->db->group_start();
			$this->db->like('log_absensi.id_pegawai', $q);
			$this->db->or_like('pegawai.nama', $q);
			$this->db->group_end();
		}
		
		if ($onlyActive) {
			$this->db->where('(log_absensi.deleted_at IS NULL OR log_absensi.deleted_at = "")');
		}
		
		return $this->db->count_all_results();
	}

	// ===== TAMBAHKAN FUNCTION HELPER INI =====
	// get nama pegawai by id
	function get_nama_pegawai($id_pegawai)
	{
		$this->db->select('nama');
		$this->db->where('id_pegawai', $id_pegawai);
		$query = $this->db->get('pegawai');
		
		if ($query->num_rows() > 0) {
			return $query->row()->nama;
		}
		return 'Tidak Diketahui';
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}

}

/* End of file Log_absensi_model.php */
/* Location: ./application/models/Log_absensi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 08:14:34 */
/* http://harviacode.com */
