<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Radius_absen_model extends CI_Model
{

	public $table = 'radius_absen';
	public $id = 'id_radius';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		return $this->db->get('radius_absen')->result();
	}

	// get data by id
	function get_by_id($id)
	{
		return $this->db->get_where('radius_absen', ['id_radius' => $id])->row();
	}

	// get total rows
	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('ukuran', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('ukuran', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert('radius_absen', $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where('id_radius', $id);
    	$this->db->update('radius_absen', $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
}

/* End of file radius_absen_absen_model.php */
/* Location: ./application/models/radius_absen_absen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 06:13:47 */
/* http://harviacode.com */
