<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Unit_kerja_model extends CI_Model
{

	public $table = 'unit_kerja';
	public $id = 'id_unit_kerja';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all() {
        $this->db->order_by('nama_unit_kerja', 'ASC');
        return $this->db->get($this->table)->result();
    }

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('nama_unit_kerja', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->or_like('nama_unit_kerja', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert('unit_kerja', $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}

}

/* End of file Unit_kerja_model.php */
/* Location: ./application/models/Unit_kerja_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 07:17:53 */
/* http://harviacode.com */
