name: Deploy Django (lancar) ke GCP Debian 11

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Django project in 'lancar' folder
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/Sipresi_Pemkot
            git pull origin main

            cd lancar
            source venv/bin/activate
            pip install -r requirements.txt

            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            sudo systemctl restart apache2
          EOF
